### ISSUE TITLE
Update counter inside transaction generates too much contention 

### ISSUE THREAD

**Issue by NicolaSpreafico** [instacount/appengine-counter#29]
Hello,
I have a counter that need to reach a preconfigured value, the (check+increment) is made inside an Objectify transaction.

The concurrency is given by parallel tasks which check the end of the counter, there are about 50 tasks in parallel.

```
static final ShardedCounterServiceImpl SHARDED_COUNTER_SERVICE;

static {
    ObjectifyFactory factory = ObjectifyService.factory();

    JodaTimeTranslators.add(factory);
    factory.register(CounterData.class);
    factory.register(CounterShardData.class);
    factory.register(CounterShardOperationData.class);

    ShardedCounterServiceConfiguration config = new ShardedCounterServiceConfiguration.Builder().withNumInitialShards(30).build();
    SHARDED_COUNTER_SERVICE = new ShardedCounterServiceImpl(MemcacheServiceFactory.getMemcacheService(), config);
}
```

 ```
private static Work<Boolean> getTransactionWork(final String batchKey, BatchLog batchLog) {
        final int totalJob = xxxxxxx;
        final String counterName = getCounterName(batchKey);

        Work<Boolean> work = new Work<Boolean>() {
            @Override
            public Boolean run() {
                Counter counter = getCounter(batchKey);
                long count = counter.getCount().longValue();

                Boolean returnValue;

                if (count + 1 == totalJob) {
                    returnValue = Boolean.TRUE;
                } else {
                    returnValue = Boolean.FALSE;
                }

                SHARDED_COUNTER_SERVICE.increment(counterName, 1L);
                return returnValue;
            }
        };
        return work;
    }
```

And here is the launch code
```
Work<Boolean> work = getTransactionWork(batchKey, BatchLogManager.getBatchLog(batchKey));
Boolean result = ObjectifyService.ofy().transact(work);
```

Sadly.. The problem is related to a contention problem for the CounterData object
```
com.googlecode.objectify.impl.TransactorNo transactNew: Optimistic concurrency failure (retrying): java.util.ConcurrentModificationException: too much contention on these datastore entities. please try again. entity group key: 
path <
  Element {
    type: "CounterData"
    name: "counter-ahZlfmF1dG9ncmlsbC1ncGUtYmUtZGV2clgLEghBbmNlc3RvciIIQmF0Y2hMb2cMCxIIQmF0Y2hMb2ciNEItZDg1ZjBmNDItZTVkMS00MTg3LTgxYzUtOWQ1OGM5OTk5MzA2LTE0NjkwMDA3ODQ2MjEM"
  }
>
```

As you can see I already increased the shards number to 30 (but I even tried 50,100 and 200) to avoid contention on the same entity. But I get the error to many often.

The thing is.. It seems that the contention is related on the counter object, not on the single shard.
When I increment a counter value, does the counter entity be updated as well or only the shard?

Inside the transaction I only GET the counter (a read operation) and then increment the value. I cannot understand why there is a contention on the CounterData entity.

**Comment by sappenin** [comment]
Hi @NicolaSpreafico,

Thanks for opening this issue!

The problem you're seeing with contention is the due to the call to **getCounter(batchKey)** being made inside of each transactional unit of work.  This call involves a Datastore access to the CounterData entity, and *may* also read all of the counter shards for the counter and collapse them into a single count.

This is definitely not something you want to do to the same counter inside of multiple/many concurrent transactions.  Also, as you discovered, increasing the number of shards won't help here either.  The shard-number increase will only help with concurrency as it relates to the increment and decrement calls, because each of these calls only involves access to a single counter shard for any given transaction (The idea being that if there enough shards, then N transactions should be able to safely access a different shard each time, or the same shard -- but stay under the Datastore concurrency limits).

The net effect of all this is that many increment/decrement operations can be performed in parallel on the same counter (in proportion to the number of shards configured for a given counter).  However, accessing the overall count of a counter is an *eventually consistent* operation.  If you need to access the count of a counter in a strongly-consisent manner, then you would not be able to use a sharding approach.  Instead, you would want to update a single number field in an entity, using a datastore transaction.  This would, of course, limit you to the datastore's transactional concurrency limits (something like ~2-5 ops/sec).

A simple fix for you might be to move this call...

`Counter counter = getCounter(batchKey);`

... outside of the transaction.  That will allow appengine-counter to give you an eventually consistent view of the counter's "count", while still allowing you to *increment* the count **inside** of a transaction.

That said, it's not completely clear what you're trying to do in your batch processing, but it looks like you're trying to stop processing if the count exceeds some threshold, and you're wanting to do that transactionally.  Unfortunately, appengine-counter isn't designed to do this.  Instead, appengine-counter allows you to transactionally increment/decrement in a consisent, atomic fashion, but getting the "count" of a counter is always eventually consistent.  

Despite this, counter "counts" are usually pretty accurate since the count is being updated in memcache on increments/decrements.  That is to say that the non-transactional _count_ of any given counter will be pretty close to the actual amount.  But this number will never be truly consistent from a datastore transactional perspective.

To get a highly consistent counter's count, I don't think you would be able to use a sharding approach with very much throughput.  This is because the true count would need to be transactionally updated on every increment/decrement, and this would simply reduce to the non-sharding approach described above. 

For your use-case, it seems like you could still use appengine-counter for batch processing, but it might help to know a little bit more about what you're trying to do.  Feel free to share more if you can.

In the meantime, I'm thinking something like this:

    final String counterName = getCounterName(batchKey);
    // accessed outside of the TX
    final Counter counter = getCounter(counterName);

    VoidWork processBatchEntry = new VoidWork() {
            @Override
            public Boolean run() {
               
                // ...do batch work in this Transaction

                // ...increment the counter in this TX.  It will complete atomically with the above batch work.
                shardedCounterService.increment(counterName, 1L);
                return null;  // ... to satisfy Java
            }
        };

       boolean keepProcessing = true;
       while(keepProcessing){
           BigInteger currentCount = shardedCounterService.getCounter(batchKey).get().getCount();
           if(currentCount.compareTo(someThreshold) > 0) {
               ObjectifyService.ofy().transact(processBatchEntry);
           } else {
               break;
           }
       }
        
Note that the above code will not allow you to process an exact amount of items, but you should use other mechanisms for that anyway.  Namely, make your batch work idempotent so that it doesn't matter if a few process more than once.  Additionally, use something in your batch entity (instead of the counter's count) to reflect if the item has been processed (if possible) and then only schedule the number that you want to be "batched."

Let me know if I can help at all on the design, especially as it relates to the use of appengine-counter.

**Comment by NicolaSpreafico** [comment]
Hello @sappenin ,
thank you for the exhaustive answer.

I try to explain to you the flow, so you can easily understand the implementation I need:
- A request spawns a certain number of tasks
- When all the tasks are finished there is a "final event" to trigger

To implement the concept of "_Am i the final task?_" I did something like this:

- the tasks are running inside a queue configured with 50 concurrent requests (but I tried with 10, 20, ... to better tune the procedure and avoid contention problem)
- After all tasks are launched, an entity is stored with the total of the tasks that has been launched (`totalJob` variable)
- When each tasks finish its work, it retrieves the value of a sharded counter. If the value has reached the total of the tasks, the final event can be triggered (and the return value is `true`). If it is not the final task, it only increment the counter value returning `false`.

The couple of operations (increment the counter) + (the counter has reached the end) are made inside an Objectify transaction to ensure the atomicity of the counter value increment.

The eventually consistent manner you described is very interesting and now I can understand if I need a strong counter this approach cannot be easily done.

> A simple fix for you might be to move this call...
> 
> Counter counter = getCounter(batchKey);
> 
> ... outside of the transaction. That will allow appengine-counter to give you an eventually consistent view of the counter's "count", while still allowing you to increment the count inside of a transaction.

In this way the `getCount()` value will be fixed on when I got the counter or at each call give me the updated couner value?

I'm unable to understand why the `ConcurrentModificationException` is made for the `CounterData` object. As you said

> The problem you're seeing with contention is the due to the call to `getCounter(batchKey)` being made inside of each transactional unit of work. This call involves a Datastore access to the CounterData entity, and may also read all of the counter shards for the counter and collapse them into a single count.

Basing on that, I'm understanding that the contention is even for READ operations, not only WRITE?
The counter and all its shards are read, this is fine, but we're talking about read operations, I do not write the `CounterData` object

---

For test purposes I tried to revert the process of "Am i the final task?" using an external tasks which is triggered every each seconds. The flow works like this:

Each task does not have a transaction anymore but simply calls the increment method of the counter
`SHARDED_COUNTER_SERVICE.increment(getCounterName(batchKey), 1L);`
I'm understanding that the `increment` method is not already inside an Objectify transaction, is automatically created, so this is why I do not use a transaction from the outside.

When all tasks has been launched by the main request, a "_monitor_" task is launched which will wait the counter to reach the end.
The implementation of the task is the following:
```
int totalJobs = xxxxxx;

Counter counter = SHARDED_COUNTER_SERVICE.getCounter(getCounterName(batchKey)).get();
long counterValue = counter.getCount().longValue();

if (counterValue < totalJobs) {
    // Send HTTP 5xx so the task will retry
} else {
    // The counter has reached the end
}
```
I configured the `RetryOptions` to wait a certain amount of seconds (for this test I used 30 seconds) removing the retry-limit (the task will retry indefinitely).

Because it is a batch process and not a synchronous one, I don't mind if the conclusion is not triggered exactly when the last task has finished. Even if there are a few minutes of delay (from when the last task finish and the monitor task starts again) is good as well.

I must say that this flow seems to work more better than the previous one, the amount of operation is decreased so the contention is under control.

The majority of the tasks are executed correctly without even a contention error, so the increment operation works fine at first attempt w/o a retry. I get this error, but is not very frequent and I consider it only as a warning not an error
```
17:41:17.644
com.theupswell.appengine.counter.service.ShardedCounterServiceImpl incrementMemcacheAtomic: Unable to update memcache counter atomically.  Retrying 10 more times...
17:41:17.649
com.theupswell.appengine.counter.service.ShardedCounterServiceImpl incrementMemcacheAtomic: Unable to update memcache counter atomically.  Retrying 9 more times...
```

I sometimes get this error, but I think it is right. It simply occours if 2 different tasks tried to increment the same counter in same time
```
com.googlecode.objectify.impl.TransactorNo transactNew: Optimistic concurrency failure for com.theupswell.appengine.counter.service.ShardedCounterServiceImpl$IncrementShardWork@1b2fe5d (retrying): java.util.ConcurrentModificationException: too much contention on these datastore entities. please try again.
```
This is also a warning, there is the `try again` note, so I can consider it as a warning.

The problem regarding the contention on the `CounterData` object is seems to be extremely rare now, I even had hard time to find it inside the logs
```
com.googlecode.objectify.impl.TransactorNo transactNew: Optimistic concurrency failure for it.noovle.ape.project.manager.batch.BatchManager$1@8cba4d (retrying): java.util.ConcurrentModificationException: too much contention on these datastore entities. please try again. entity group key: app: "e~xxxxxxxx"
path <
  Element {
    type: "CounterData"
    name: "counter-ahZlfmF1dG9ncmlsbC1ncGUtYmUtZGV2clgLEghBbmNlc3RvciIIQmF0Y2hMb2cMCxIIQmF0Y2hMb2ciNEItMzAzYTY5ZDgtOGU3OS00OTJiLTgzZTYtMjE3YjliMmM5Nzk0LTE0NjkwMjE3NzU4NTEM"
  }
>
```

I also solved the problem of the `eventual consistency` because if when I access the counter value is not consistent, the next try will get the proper value.

From the first attempts this flow seems to work better, the transaction operations are now reduced to only increment the value. This can be even a way to lighten the concurrent operations with the datastore.

**Comment by sappenin** [comment]
Hi @NicolaSpreafico,

It sounds like you've figured out a good solution.  I have a few thoughts/answers-to-questions, but overall I think your solution can work.

> I'm unable to understand why the ConcurrentModificationException is made for the CounterData object ... I'm understanding that the contention is even for READ operations, not only WRITE?  

Yes, but only if you're trying to write an entity being read in a TX.  In your case, since you were reading a counter in a transaction (and internally appengine-counter will often read all of the shards to aggregate the counts), then any other thread trying to increment a shard in that counter would fail.  Quoting from the docs [Transactions: Isolation and Consistency](https://cloud.google.com/appengine/docs/java/datastore/transactions#Java_Isolation_and_consistency), "_Inside of transactions, serializable isolation is enforced. This means that another transaction cannot concurrently modify the data that is read or modified by this transaction._"

> I'm understanding that the increment method is not already inside an Objectify transaction, is automatically created, so this is why I do not use a transaction from the outside.

Yes, each increment/decrement is performed in a transaction so the shard update is guaranteed to be consistent.  This is why you'll occasionally see the error "_Unable to update memcache counter atomically.  Retrying 10 more times..._"  It means the library attempted to update a shard, but the shard was being updated by another thread.  This is expected -- we're using a sharding strategy because we expect many requests to increment the same counter, and if there aren't enough shards, we'll see contention.  The library retries up to 10 times since failing immediately wouldn't necessarily add any value (the library or a client would likely just try again anyway).

> I sometimes get this error, but I think it is right. It simply occours if 2 different tasks tried to increment the same counter in same time ... This is also a warning, there is the try again note, so I can consider it as a warning.

Yes, see my comment directly above.

> The problem regarding the contention on the CounterData object is seems to be extremely rare now, I even had hard time to find it inside the logs

This is good news, though it's not clear why this would be happening at all.  Might be worth looking at your code paths just to be sure.  Are you updating the Counter somewhere, or possibly calling getCounter() inside of a transaction?

> When all tasks has been launched by the main request, a "monitor" task is launched which will wait the counter to reach the end.

I like your idea of the _monitor_ task.  I think this will work in most cases, but there are some edge cases you should be aware of.  

For example, the TaskQueue system generally only issues a request to handle a task once.  However, in certain circumstances, tasks can be fired more than once.  See [here](https://cloud.google.com/appengine/docs/java/taskqueue/push/creating-handlers#writing_a_push_task_request_handler).  In your design, if the same task is fired twice, it will increment the counter, which may prompt your monitor to "finish" before all of the tasks have been processed.  Here, you might "miss" a task.  If this is OK on the rare occasion, then you should be fine.  But if this is not acceptable, you might want to reconsider your design.

One idea I have is to leave your "monitor" task as-is, but tweak your handler code to make sure it is idempotent.  There are various ways to do this, but one thought I have is to add a UUID to each task payload when it is scheduled.  In your task handler, you could use the Entity Lock pattern to make sure your multiple tasks are only executed once.  

To do this, you would store an entity that has the task's UUID (as a string) as its Key value.  On subsequent task handler requests, the code will do a strongly consistent GET, and if the entity exists throw an exception (your task handler would catch this exception, and return normally to complete the duplicate task).  

Conversely, if the lock entity doesn't exist, your task handler will create it and let the thread continue operating.  In your case, this would act as a semaphore for your task handlers and theoretically only allow one task handler request to handle the batch, while any other handler requests with the same UUID would be ignored.

Here's some pseudo-code: 

TASK SCHEDULER
```
final String uuid = UUID.randomUuid().toString();
payload.setIdempotencyToken(uuid);
```

TASK HANDLER

```
VoidWork batchWork = new VoidWork() {
        @Override
        public Boolean run() {

            // ...Create a Key<IdempotencyEntity> using the UUID from the task.
            // ...Attempt to reserve a lock using ObjectifyEntityLockHelper (see links below)
            // If (the lock reservation fails): this task has been executed already.  Return 200.
            // else: 
            //   try {
            //     process the batch
            //     increment the sharded counter.
            //     return 200
            //    } 
            //    catch(Exception e) {
            //      ... remove the lock so that future task handler requests retry the batch
            //      ObjectifyEntityLockHelper.removeLock();
            //    }
        }
    };

ObjectifyService.ofy().transact(batchWork);
```

This won't be a perfect solution either, but it will be close.  The reason it's not perfect is that it's possible two tasks are running at the same time with the same UUID.  The first task has successfully reserved an EntityLock, and the second task fails to acquire this lock (since the first thread has it).  The second tasks returns 200 and does nothing.  If the first task fails without processing the batch, _and_ also fails to release the lock, then that task will never be completed because the next time the TaskQueue executes, it will see the lock, and return 200.  If you wanted to be more advanced, you could add a "taskCompleted" boolean to your entity lock and then use that as a secondary flag to let the task handler know if a task was completed (?)

Here are some links to some helper code I've written that will help with the EntityLock pattern:

[Objectify EntityLocks](https://github.com/sappenin/appengine-utils/tree/master/src/main/java/com/sappenin/utils/appengine/data/locks)

Hope that helps!

**Comment by NicolaSpreafico** [comment]
Hi @sappenin 

>  In your design, if the same task is fired twice, it will increment the counter, which may prompt your monitor to "finish" before all of the tasks have been processed. Here, you might "miss" a task. 
This cannot happen because the first thing that the task check before event starts to work if it is already been processed (There is a support entity for each task which will write the status and the end of operation).

**Comment by sappenin** [comment]
Sounds like you have this figured out.  Feel free to re-open if not.  Thanks!
