### ISSUE TITLE
IncrementGet

### ISSUE THREAD

**Issue by ThomasDeLetter** [instacount/appengine-counter#31]
When doing an increment immediately followed by a getcount, will this be atomic. Can I use this value as an id for example? 
Do I have to do this in a transaction?

**Comment by sappenin** [comment]
Hi @ThomasDeLetter, thanks for posting your question.

In general the answer is yes: increment and decrement operations are atomic if the operation responds without throwing certain kinds of Datastore exception (e.g., `DatastoreFailureException` and `DatastoreTimeoutException`).  This is a subtle edge-case where the Google Datastore will report that the operation failed, but in reality the Datastore operation may have succeeded (see [Data Consistency](https://cloud.google.com/datastore/docs/concepts/structuring_for_strong_consistency) near the text "_...If your application receives an exception when attempting to commit a transaction..._")

This is a short-coming of the current `appengine-counter` interface design -- in these cases, there's no good way to know if your increment succeeded.  Your only recourse is to retry the increment until you don't receive a Datastore exception, but you would need to use `ShardedCounterService#increment(counterName, amount, shardNumber, incrementUuid)`, which would allow you to catch the Datastore exception and retry in an idempotent fashion.  However, you would need to duplicate the random-shard-picking logic found in the implementation since that method requires you to specify the Shard to increment/decrement in order to enforce idempotence.  

That said, even if the ShardedCounter interface were improved to help callers get around this issue, I would advise against using this library to generate identifiers.  While the `ShardedCounter#getCounter` operations are _usually_ consistent, they're not always.  At best, the `getCounter` operations should be considered _eventually consistent_ because the counter shards stored in the Datastore are fronted by memcache for accessing counts.  Occasionally, the counts reported by memcache to the caller of ShardedCounterService can be incorrect.  The library does it's best to always keep memcache in sync with the actual counter shards, but since memcache isn't actually connected to the CounterShards, sometimes it can get out of sync for a bit until the cache times out and the count is recalculated.

In my mind, the intended usage scenario for this library is one where you want to guarantee that an increment/decrement is applied (notwithstanding the above), but can tolerate getting the _actual_ count ~99% of the time, and a slightly-out-of-date count some other percent of the time whenever memcache is latent/flaky/restarted, etc.

If you need to generate identifiers, I would suggest using the Datastore to do that work for you.  For example, would the [Datastore allocateIds](https://cloud.google.com/appengine/docs/java/javadoc/com/google/appengine/api/datastore/DatastoreService.html#allocateIds-java.lang.String-long-) method work for you?

**Comment by sappenin** [comment]
I've opened #32 as a task to track the improvement to `ShardedCounterService` that I outlined above.

**Comment by ThomasDeLetter** [comment]
Thanks for the reply! 

I redesigned my project and i now work with allocateids. 

Do you know by any chance if the allocateids are increasing? They do not need to be consecutive.

**Comment by sappenin** [comment]
I'm not 100% sure on the allocateids, but I believe a block of ids is reserved, so they will not be consecutive, but they will be unique.
